/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoffeeAndCenterTablesRouteImport } from './routes/coffee-and-center-tables'
import { Route as CartsRouteImport } from './routes/carts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserLoginRouteImport } from './routes/user/login'

const CoffeeAndCenterTablesRoute = CoffeeAndCenterTablesRouteImport.update({
  id: '/coffee-and-center-tables',
  path: '/coffee-and-center-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const CartsRoute = CartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carts': typeof CartsRoute
  '/coffee-and-center-tables': typeof CoffeeAndCenterTablesRoute
  '/user/login': typeof UserLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carts': typeof CartsRoute
  '/coffee-and-center-tables': typeof CoffeeAndCenterTablesRoute
  '/user/login': typeof UserLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carts': typeof CartsRoute
  '/coffee-and-center-tables': typeof CoffeeAndCenterTablesRoute
  '/user/login': typeof UserLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carts' | '/coffee-and-center-tables' | '/user/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carts' | '/coffee-and-center-tables' | '/user/login'
  id: '__root__' | '/' | '/carts' | '/coffee-and-center-tables' | '/user/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartsRoute: typeof CartsRoute
  CoffeeAndCenterTablesRoute: typeof CoffeeAndCenterTablesRoute
  UserLoginRoute: typeof UserLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coffee-and-center-tables': {
      id: '/coffee-and-center-tables'
      path: '/coffee-and-center-tables'
      fullPath: '/coffee-and-center-tables'
      preLoaderRoute: typeof CoffeeAndCenterTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carts': {
      id: '/carts'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof CartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartsRoute: CartsRoute,
  CoffeeAndCenterTablesRoute: CoffeeAndCenterTablesRoute,
  UserLoginRoute: UserLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
