import { ProductItem } from "@/components/ProductGridSection";

export const diningTableItems: ProductItem[] = [
  {
    id: "minimal-epoxy-6-seater",
    href: "https://www.woodensure.com/item/minimal-epoxy-resin-6-seater-dining-table",
    title: "Minimal 6 Seater Dining Table – Epoxy Resin & Wood",
    img: "https://www.woodensure.com/assets/images/thumbnails/1764228732viEWRdms.avif",
    imgDesktop: "https://www.woodensure.com/assets/images/products/1764228732zaseMT3K.avif",
    price: "₹28499",
    priceOriginal: "₹45000",
    discountText: "Save 37%",
  },
  {
    id: "marble-top-4-seater",
    href: "https://www.woodensure.com/item/woodensure-marble-top-rectangular-4-seater-dining-table-eldd559335",
    title: "Marble Top Rectangular 4 Seater Dining Table",
    img: "https://www.woodensure.com/assets/images/thumbnails/17659654640D2z9Rhu.avif",
    imgDesktop: "https://www.woodensure.com/assets/images/products/17659654644tLvOKv5.avif",
    price: "₹35500",
    priceOriginal: "₹56000",
    discountText: "Save 37%",
  },
  {
    id: "zorynglow-sheesham-set",
    href: "https://www.woodensure.com/item/zorynglow-sheesham-dining-table-set-solid-wood-with-cushioned-chairs-4-seater-set-dining-room-mqe2131edz",
    title: "ZorynGlow Sheesham Dining Table Set | Solid Wood with Cushioned Chairs | 4-Seater",
    img: "https://www.woodensure.com/assets/images/thumbnails/1745652145TdDXZqUY.jpg",
    imgDesktop: "https://www.woodensure.com/assets/images/products/1745652145zxlTFG9j.jpg",
    price: "₹29000",
    priceOriginal: "₹43000",
    discountText: "Save 33%",
  },
  {
    id: "live-edge-natural-finish",
    href: "https://www.woodensure.com/item/live-edge-dining-table-natural-finish-28y96177oi",
    title: "Natural finish live edge dining table for elegant dining spaces",
    img: "https://www.woodensure.com/assets/images/thumbnails/1707479803Ry6dAZ6i.jpg",
    imgDesktop: "https://www.woodensure.com/assets/images/products/1707479803Uz1DewIA.png",
    price: "₹34500",
    priceOriginal: "₹69799",
    discountText: "Save 51%",
  },
  {
    id: "oval-live-edge-dining",
    href: "https://www.woodensure.com/item/woodensure-oval-live-edge-dining-table-zdy6039qvz",
    title: "Live Edge Wood Oval Shape Dining Table, Epoxy Resin Egg Shape Table",
    img: "https://www.woodensure.com/assets/images/thumbnails/1707837776DNv3fPgn.jpg",
    imgDesktop: "https://www.woodensure.com/assets/images/products/1707837776Ro49VQ8I.png",
    price: "₹99000",
    priceOriginal: "₹129000",
    discountText: "Save 23%",
  },
];
