import { ProductItem } from "@/components/ProductGridSection";

export const marbleDiningTableItems: ProductItem[] = [
  {
    id: "marble-top-rectangular-4-seater",
    href: "https://www.woodensure.com/item/woodensure-marble-top-rectangular-4-seater-dining-table-eldd559335",
    title: "Marble Top Rectangular 4 Seater Dining Table",
    img: "https://www.woodensure.com/assets/images/thumbnails/17659654640D2z9Rhu.avif",
    imgDesktop: "https://www.woodensure.com/assets/images/products/17659654644tLvOKv5.avif",
    price: "₹35500",
    priceOriginal: "₹56000",
    discountText: "Save 37%",
  },
  {
    id: "6-seater-marble-oval",
    href: "https://www.woodensure.com/item/6-seater-marble-top-dining-table-rectangular-bglc553770",
    title: "6 Seater Marble Top Dining Table - Oval Shape",
    img: "https://www.woodensure.com/assets/images/thumbnails/17659646397yrLa00k.avif",
    imgDesktop: "https://www.woodensure.com/assets/images/products/17659646398babVefR.avif",
    price: "₹51500",
    priceOriginal: "₹128500",
    discountText: "Save 60%",
  },
  {
    id: "6-seater-marble-oval-set",
    href: "https://www.woodensure.com/item/woodensure-6-seater-marble-top-rectangular-dining-table-set-95yw547460",
    title: "6 Seater Marble Top Oval Dining Table",
    img: "https://www.woodensure.com/assets/images/thumbnails/1765962266WWhXbJjM.avif",
    imgDesktop: "https://www.woodensure.com/assets/images/products/1765962266bPrRaMPt.avif",
    price: "₹51500",
    priceOriginal: "₹159836",
    discountText: "Save 68%",
  },
  {
    id: "4-seater-round-dining",
    href: "https://www.woodensure.com/item/woodensure-4-seater-round-dining-table-jjaz247877",
    title: "4 Seater Round Dining Table",
    img: "https://www.woodensure.com/assets/images/thumbnails/1766039102v3QmwHUg.avif",
    imgDesktop: "https://www.woodensure.com/assets/images/products/1766039102wfbQbmEl.avif",
    price: "₹49500",
    priceOriginal: "₹80000",
    discountText: "Save 38%",
  },
  {
    id: "terraforma-round-stone",
    href: "https://www.woodensure.com/item/terraforma-round-stone-dining-table-4-seater-stone-modern-dining",
    title: "TerraForma Round Stone Dining Table – Natural Terrazzo Stone Top & Solid Mango Wood",
    img: "https://www.woodensure.com/assets/images/thumbnails/1757670330LppW2zG6.jpg",
    imgDesktop: "https://www.woodensure.com/assets/images/products/1757670330LZxsh4Nz.jpg",
    price: "₹48000",
    priceOriginal: "₹122500",
    discountText: "Save 61%",
  },
];
